name: "Push Docs"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:469f14ef0fade3ae4c07e4977638fdf3afc29e08
    - run: nix 
